//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationTesting_CorConnect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggerMesages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerMesages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomationTesting_CorConnect.Resources.LoggerMesages", typeof(LoggerMesages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddingDataForTestCase {0}.
        /// </summary>
        internal static string AddingDataForTestCase {
            get {
                return ResourceManager.GetString("AddingDataForTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding TestCase Property {0}={1}.
        /// </summary>
        internal static string AddingTestCaseProperty {
            get {
                return ResourceManager.GetString("AddingTestCaseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Excel Connection.
        /// </summary>
        internal static string ClosingExcelConnection {
            get {
                return ResourceManager.GetString("ClosingExcelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Application Context.
        /// </summary>
        internal static string CreatingNewApplicationContext {
            get {
                return ResourceManager.GetString("CreatingNewApplicationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Part Number: {0}.
        /// </summary>
        internal static string DeletingPart {
            get {
                return ResourceManager.GetString("DeletingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Enviorment Data.
        /// </summary>
        internal static string EmptyEnviormentData {
            get {
                return ResourceManager.GetString("EmptyEnviormentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Extension=&apos;{0}&apos;.
        /// </summary>
        internal static string ExcelFileExtension {
            get {
                return ResourceManager.GetString("ExcelFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Query.
        /// </summary>
        internal static string ExecutingQuery {
            get {
                return ResourceManager.GetString("ExecutingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Expected message: [{0}], Actual message: [{1}].
        /// </summary>
        internal static string ExpectedMessage {
            get {
                return ResourceManager.GetString("ExpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Expected value: [{0}], Actual value: [{1}].
        /// </summary>
        internal static string ExpectedValue {
            get {
                return ResourceManager.GetString("ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializingPage= .
        /// </summary>
        internal static string InitializingPage {
            get {
                return ResourceManager.GetString("InitializingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading EnviormentData.
        /// </summary>
        internal static string LoadingEnviormentData {
            get {
                return ResourceManager.GetString("LoadingEnviormentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Test Data.
        /// </summary>
        internal static string LoadingTestData {
            get {
                return ResourceManager.GetString("LoadingTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping {0}={1}.
        /// </summary>
        internal static string MappingData {
            get {
                return ResourceManager.GetString("MappingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Excel Connection.
        /// </summary>
        internal static string OpenningExcelconnection {
            get {
                return ResourceManager.GetString("OpenningExcelconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Sheet=&apos;{0}&apos;.
        /// </summary>
        internal static string ReadingSheet {
            get {
                return ResourceManager.GetString("ReadingSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Test Input Data.
        /// </summary>
        internal static string ReadingTestInputData {
            get {
                return ResourceManager.GetString("ReadingTestInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading User Data.
        /// </summary>
        internal static string ReadingUserData {
            get {
                return ResourceManager.GetString("ReadingUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreiving Data For Test Case: {0}.
        /// </summary>
        internal static string RetrivingDataForTC {
            get {
                return ResourceManager.GetString("RetrivingDataForTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retriving Data From DB.
        /// </summary>
        internal static string RetrivingDataFromDB {
            get {
                return ResourceManager.GetString("RetrivingDataFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Application Context.
        /// </summary>
        internal static string ReturningApplicationContext {
            get {
                return ResourceManager.GetString("ReturningApplicationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning DataAccess Layer Instance.
        /// </summary>
        internal static string ReturningDALInstance {
            get {
                return ResourceManager.GetString("ReturningDALInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturningLoggingContext.
        /// </summary>
        internal static string ReturningLoggingContext {
            get {
                return ResourceManager.GetString("ReturningLoggingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Test.
        /// </summary>
        internal static string StartingTest {
            get {
                return ResourceManager.GetString("StartingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating {0} File Download.
        /// </summary>
        internal static string ValidatingFileDownload {
            get {
                return ResourceManager.GetString("ValidatingFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Grid Buttons.
        /// </summary>
        internal static string ValidatingGridButtons {
            get {
                return ResourceManager.GetString("ValidatingGridButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Group Panel.
        /// </summary>
        internal static string ValidatingGroupPanel {
            get {
                return ResourceManager.GetString("ValidatingGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Hyperlink.
        /// </summary>
        internal static string ValidatingHyperlink {
            get {
                return ResourceManager.GetString("ValidatingHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Nested Grid Buttons.
        /// </summary>
        internal static string ValidatingNestedGridButtons {
            get {
                return ResourceManager.GetString("ValidatingNestedGridButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating nested grid group panel.
        /// </summary>
        internal static string ValidatingNestedGroupPanel {
            get {
                return ResourceManager.GetString("ValidatingNestedGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating nested table page counter.
        /// </summary>
        internal static string ValidatingNestedPageCounter {
            get {
                return ResourceManager.GetString("ValidatingNestedPageCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating nested table headers.
        /// </summary>
        internal static string ValidatingNestedTableHeaders {
            get {
                return ResourceManager.GetString("ValidatingNestedTableHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Page Buttons.
        /// </summary>
        internal static string ValidatingPageButtons {
            get {
                return ResourceManager.GetString("ValidatingPageButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Page Caption.
        /// </summary>
        internal static string ValidatingPageCaption {
            get {
                return ResourceManager.GetString("ValidatingPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Page Counter.
        /// </summary>
        internal static string ValidatingPageCounter {
            get {
                return ResourceManager.GetString("ValidatingPageCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Page Fields.
        /// </summary>
        internal static string ValidatingPageFields {
            get {
                return ResourceManager.GetString("ValidatingPageFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating right panel to be empty.
        /// </summary>
        internal static string ValidatingRightPanelEmpty {
            get {
                return ResourceManager.GetString("ValidatingRightPanelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Selected Counter.
        /// </summary>
        internal static string ValidatingSelectedCounter {
            get {
                return ResourceManager.GetString("ValidatingSelectedCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Table Headers.
        /// </summary>
        internal static string ValidatingTableHeaders {
            get {
                return ResourceManager.GetString("ValidatingTableHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Tabs.
        /// </summary>
        internal static string ValidatingTabs {
            get {
                return ResourceManager.GetString("ValidatingTabs", resourceCulture);
            }
        }
    }
}
