//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationTesting_CorConnect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomationTesting_CorConnect.Resources.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration Program.
        /// </summary>
        internal static string AccelerationProgram {
            get {
                return ResourceManager.GetString("AccelerationProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Maintenance.
        /// </summary>
        internal static string AccountMaintenance {
            get {
                return ResourceManager.GetString("AccountMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Maintenance Aspx.
        /// </summary>
        internal static string AccountMaintenanceAspx {
            get {
                return ResourceManager.GetString("AccountMaintenanceAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status Change Report.
        /// </summary>
        internal static string AccountStatusChangeReport {
            get {
                return ResourceManager.GetString("AccountStatusChangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Cross Reference Entry.
        /// </summary>
        internal static string AddNewCrossReferenceEntry {
            get {
                return ResourceManager.GetString("AddNewCrossReferenceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aged Invoice Report.
        /// </summary>
        internal static string AgedInvoiceReport {
            get {
                return ResourceManager.GetString("AgedInvoiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Group Approvers Report.
        /// </summary>
        internal static string AgencyGroupApproversReport {
            get {
                return ResourceManager.GetString("AgencyGroupApproversReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASN.
        /// </summary>
        internal static string ASN {
            get {
                return ResourceManager.GetString("ASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Entity Chart.
        /// </summary>
        internal static string AssignEntityChart {
            get {
                return ResourceManager.GetString("AssignEntityChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Entity Function.
        /// </summary>
        internal static string AssignEntityFunction {
            get {
                return ResourceManager.GetString("AssignEntityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign User Charts.
        /// </summary>
        internal static string AssignUserCharts {
            get {
                return ResourceManager.GetString("AssignUserCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Request Status.
        /// </summary>
        internal static string BatchRequestStatus {
            get {
                return ResourceManager.GetString("BatchRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Schedule Management.
        /// </summary>
        internal static string BillingScheduleManagement {
            get {
                return ResourceManager.GetString("BillingScheduleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks Maintenance.
        /// </summary>
        internal static string BookmarksMaintenance {
            get {
                return ResourceManager.GetString("BookmarksMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Actions.
        /// </summary>
        internal static string BulkActions {
            get {
                return ResourceManager.GetString("BulkActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Report.
        /// </summary>
        internal static string CashFlowReport {
            get {
                return ResourceManager.GetString("CashFlowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Documents.
        /// </summary>
        internal static string CommunityDocuments {
            get {
                return ResourceManager.GetString("CommunityDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Fee Report.
        /// </summary>
        internal static string CommunityFeeReport {
            get {
                return ResourceManager.GetString("CommunityFeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Authorization.
        /// </summary>
        internal static string CreateAuthorization {
            get {
                return ResourceManager.GetString("CreateAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invoice Watch List.
        /// </summary>
        internal static string CreateInvoiceWatchList {
            get {
                return ResourceManager.GetString("CreateInvoiceWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New MasterBilling Statement Configuration.
        /// </summary>
        internal static string CreateMasterBillingStatementConfiguration {
            get {
                return ResourceManager.GetString("CreateMasterBillingStatementConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Billing Schedule Management.
        /// </summary>
        internal static string CreateNewBillingScheduleManagement {
            get {
                return ResourceManager.GetString("CreateNewBillingScheduleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Entity.
        /// </summary>
        internal static string CreateNewEntity {
            get {
                return ResourceManager.GetString("CreateNewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Payment Term.
        /// </summary>
        internal static string CreateNewPaymentTerm {
            get {
                return ResourceManager.GetString("CreateNewPaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit History.
        /// </summary>
        internal static string CreditHistory {
            get {
                return ResourceManager.GetString("CreditHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Discount Date Report.
        /// </summary>
        internal static string DealerDiscountDateReport {
            get {
                return ResourceManager.GetString("DealerDiscountDateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Due Date Report.
        /// </summary>
        internal static string DealerDueDateReport {
            get {
                return ResourceManager.GetString("DealerDueDateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Invoice Detail.
        /// </summary>
        internal static string DealerInvoiceDetail {
            get {
                return ResourceManager.GetString("DealerInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Invoice Pre-Approval Report.
        /// </summary>
        internal static string DealerInvoicePreApprovalReport {
            get {
                return ResourceManager.GetString("DealerInvoicePreApprovalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Invoices.
        /// </summary>
        internal static string DealerInvoices {
            get {
                return ResourceManager.GetString("DealerInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Invoice Transaction Lookup.
        /// </summary>
        internal static string DealerInvoiceTransactionLookup {
            get {
                return ResourceManager.GetString("DealerInvoiceTransactionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Locations.
        /// </summary>
        internal static string DealerLocations {
            get {
                return ResourceManager.GetString("DealerLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Lookup.
        /// </summary>
        internal static string DealerLookup {
            get {
                return ResourceManager.GetString("DealerLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Part Summary - Fleet Bill To.
        /// </summary>
        internal static string DealerPartSummaryFleetBillTo {
            get {
                return ResourceManager.GetString("DealerPartSummaryFleetBillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Part Summary - Fleet Location.
        /// </summary>
        internal static string DealerPartSummaryFleetLocation {
            get {
                return ResourceManager.GetString("DealerPartSummaryFleetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer PO/POQ Transaction Lookup.
        /// </summary>
        internal static string DealerPOPOQTransactionLookup {
            get {
                return ResourceManager.GetString("DealerPOPOQTransactionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Pre Authorization.
        /// </summary>
        internal static string DealerPreAuthorization {
            get {
                return ResourceManager.GetString("DealerPreAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Purchases Report.
        /// </summary>
        internal static string DealerPurchasesReport {
            get {
                return ResourceManager.GetString("DealerPurchasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Release Invoices.
        /// </summary>
        internal static string DealerReleaseInvoices {
            get {
                return ResourceManager.GetString("DealerReleaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Sales Summary - Bill To.
        /// </summary>
        internal static string DealerSalesSummaryBillTo {
            get {
                return ResourceManager.GetString("DealerSalesSummaryBillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Sales Summary - Location.
        /// </summary>
        internal static string DealerSalesSummaryLocation {
            get {
                return ResourceManager.GetString("DealerSalesSummaryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Statements.
        /// </summary>
        internal static string DealerStatements {
            get {
                return ResourceManager.GetString("DealerStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquent Fee Invoice Setup.
        /// </summary>
        internal static string DelinquentFeeInvoiceSetup {
            get {
                return ResourceManager.GetString("DelinquentFeeInvoiceSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Preferences.
        /// </summary>
        internal static string DisplayPreferences {
            get {
                return ResourceManager.GetString("DisplayPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disputes.
        /// </summary>
        internal static string Disputes {
            get {
                return ResourceManager.GetString("Disputes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Statement Report.
        /// </summary>
        internal static string DraftStatementReport {
            get {
                return ResourceManager.GetString("DraftStatementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunning Status.
        /// </summary>
        internal static string DunningStatus {
            get {
                return ResourceManager.GetString("DunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit MasterBilling Statement Configuration.
        /// </summary>
        internal static string EditMasterBillingStatementConfiguration {
            get {
                return ResourceManager.GetString("EditMasterBillingStatementConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        internal static string Enrollment {
            get {
                return ResourceManager.GetString("Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Cross Reference Maintenance.
        /// </summary>
        internal static string EntityCrossReferenceMaintenance {
            get {
                return ResourceManager.GetString("EntityCrossReferenceMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Group Maintenance.
        /// </summary>
        internal static string EntityGroupMaintenance {
            get {
                return ResourceManager.GetString("EntityGroupMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Management.
        /// </summary>
        internal static string FeeManagement {
            get {
                return ResourceManager.GetString("FeeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Management Aspx.
        /// </summary>
        internal static string FeeManagementAspx {
            get {
                return ResourceManager.GetString("FeeManagementAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Bill To Sales Summary.
        /// </summary>
        internal static string FleetBillToSalesSummary {
            get {
                return ResourceManager.GetString("FleetBillToSalesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Credit.
        /// </summary>
        internal static string FleetCredit {
            get {
                return ResourceManager.GetString("FleetCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Credit Limit.
        /// </summary>
        internal static string FleetCreditLimit {
            get {
                return ResourceManager.GetString("FleetCreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Credit Limit Watch List Report.
        /// </summary>
        internal static string FleetCreditLimitWatchListReport {
            get {
                return ResourceManager.GetString("FleetCreditLimitWatchListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Discount Date Report.
        /// </summary>
        internal static string FleetDiscountDateReport {
            get {
                return ResourceManager.GetString("FleetDiscountDateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Due Date Report.
        /// </summary>
        internal static string FleetDueDateReport {
            get {
                return ResourceManager.GetString("FleetDueDateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Invoice Detail Report.
        /// </summary>
        internal static string FleetInvoiceDetailReport {
            get {
                return ResourceManager.GetString("FleetInvoiceDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Invoice Pre-Approval Report.
        /// </summary>
        internal static string FleetInvoicePreApprovalReport {
            get {
                return ResourceManager.GetString("FleetInvoicePreApprovalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Invoices.
        /// </summary>
        internal static string FleetInvoices {
            get {
                return ResourceManager.GetString("FleetInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Invoice Transaction Lookup.
        /// </summary>
        internal static string FleetInvoiceTransactionLookup {
            get {
                return ResourceManager.GetString("FleetInvoiceTransactionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Locations.
        /// </summary>
        internal static string FleetLocations {
            get {
                return ResourceManager.GetString("FleetLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Location Sales Summary.
        /// </summary>
        internal static string FleetLocationSalesSummary {
            get {
                return ResourceManager.GetString("FleetLocationSalesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Lookup.
        /// </summary>
        internal static string FleetLookup {
            get {
                return ResourceManager.GetString("FleetLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Master Invoices/Statements.
        /// </summary>
        internal static string FleetMasterInvoicesStatements {
            get {
                return ResourceManager.GetString("FleetMasterInvoicesStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Part Category Sales Summary - Bill To.
        /// </summary>
        internal static string FleetPartCategorySalesSummaryBillTo {
            get {
                return ResourceManager.GetString("FleetPartCategorySalesSummaryBillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Part Category Sales Summary - Location.
        /// </summary>
        internal static string FleetPartCategorySalesSummaryLocation {
            get {
                return ResourceManager.GetString("FleetPartCategorySalesSummaryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Parts Cross Reference.
        /// </summary>
        internal static string FleetPartsCrossReference {
            get {
                return ResourceManager.GetString("FleetPartsCrossReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Part Summary - Bill To.
        /// </summary>
        internal static string FleetPartSummaryBillTo {
            get {
                return ResourceManager.GetString("FleetPartSummaryBillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Part Summary - Location.
        /// </summary>
        internal static string FleetPartSummaryLocation {
            get {
                return ResourceManager.GetString("FleetPartSummaryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet PO/POQ Transaction Lookup.
        /// </summary>
        internal static string FleetPOPOQTransactionLookup {
            get {
                return ResourceManager.GetString("FleetPOPOQTransactionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Pre Authorization.
        /// </summary>
        internal static string FleetPreAuthorization {
            get {
                return ResourceManager.GetString("FleetPreAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Release Invoices.
        /// </summary>
        internal static string FleetReleaseInvoices {
            get {
                return ResourceManager.GetString("FleetReleaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Sales Summary - Bill To.
        /// </summary>
        internal static string FleetSalesSummaryBillTo {
            get {
                return ResourceManager.GetString("FleetSalesSummaryBillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Sales Summary - Location.
        /// </summary>
        internal static string FleetSalesSummaryLocation {
            get {
                return ResourceManager.GetString("FleetSalesSummaryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Statements.
        /// </summary>
        internal static string FleetStatements {
            get {
                return ResourceManager.GetString("FleetStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise Code Management.
        /// </summary>
        internal static string FranchiseCodeManagement {
            get {
                return ResourceManager.GetString("FranchiseCodeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Draft Statements.
        /// </summary>
        internal static string GPDraftStatements {
            get {
                return ResourceManager.GetString("GPDraftStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Margin Credit Report.
        /// </summary>
        internal static string GrossMarginCreditReport {
            get {
                return ResourceManager.GetString("GrossMarginCreditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Relationships Maintenance.
        /// </summary>
        internal static string GroupRelationshipsMaintenance {
            get {
                return ResourceManager.GetString("GroupRelationshipsMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercommunity Invoice Report.
        /// </summary>
        internal static string IntercommunityInvoiceReport {
            get {
                return ResourceManager.GetString("IntercommunityInvoiceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail Report.
        /// </summary>
        internal static string InvoiceDetailReport {
            get {
                return ResourceManager.GetString("InvoiceDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discrepancy.
        /// </summary>
        internal static string InvoiceDiscrepancy {
            get {
                return ResourceManager.GetString("InvoiceDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discrepancy History.
        /// </summary>
        internal static string InvoiceDiscrepancyHistory {
            get {
                return ResourceManager.GetString("InvoiceDiscrepancyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Download.
        /// </summary>
        internal static string InvoiceDownload {
            get {
                return ResourceManager.GetString("InvoiceDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Download Setup.
        /// </summary>
        internal static string InvoiceDownloadSetup {
            get {
                return ResourceManager.GetString("InvoiceDownloadSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Entry.
        /// </summary>
        internal static string InvoiceEntry {
            get {
                return ResourceManager.GetString("InvoiceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice History.
        /// </summary>
        internal static string InvoiceHistory {
            get {
                return ResourceManager.GetString("InvoiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Options Aspx.
        /// </summary>
        internal static string InvoiceOptionsAspx {
            get {
                return ResourceManager.GetString("InvoiceOptionsAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Watch List.
        /// </summary>
        internal static string InvoiceWatchList {
            get {
                return ResourceManager.GetString("InvoiceWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item Report.
        /// </summary>
        internal static string LineItemReport {
            get {
                return ResourceManager.GetString("LineItemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Summary.
        /// </summary>
        internal static string LocationSummary {
            get {
                return ResourceManager.GetString("LocationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Status.
        /// </summary>
        internal static string LoyaltyStatus {
            get {
                return ResourceManager.GetString("LoyaltyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Approvals.
        /// </summary>
        internal static string ManageApprovals {
            get {
                return ResourceManager.GetString("ManageApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Custom Fields.
        /// </summary>
        internal static string ManageCustomFields {
            get {
                return ResourceManager.GetString("ManageCustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Custom Fields Aspx.
        /// </summary>
        internal static string ManageCustomFieldsAspx {
            get {
                return ResourceManager.GetString("ManageCustomFieldsAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Delinquent Fee.
        /// </summary>
        internal static string ManageDelinquentFee {
            get {
                return ResourceManager.GetString("ManageDelinquentFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Disputes.
        /// </summary>
        internal static string ManageDisputes {
            get {
                return ResourceManager.GetString("ManageDisputes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payment Acceleration.
        /// </summary>
        internal static string ManagePaymentAcceleration {
            get {
                return ResourceManager.GetString("ManagePaymentAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payment Terms.
        /// </summary>
        internal static string ManagePaymentTerms {
            get {
                return ResourceManager.GetString("ManagePaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rebates.
        /// </summary>
        internal static string ManageRebates {
            get {
                return ResourceManager.GetString("ManageRebates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tax Exemptions.
        /// </summary>
        internal static string ManageTaxExemptions {
            get {
                return ResourceManager.GetString("ManageTaxExemptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Notifications.
        /// </summary>
        internal static string ManageUserNotifications {
            get {
                return ResourceManager.GetString("ManageUserNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master/Billing Statement Configuration.
        /// </summary>
        internal static string MasterBillingStatementConfiguration {
            get {
                return ResourceManager.GetString("MasterBillingStatementConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Summary.
        /// </summary>
        internal static string MemberSummary {
            get {
                return ResourceManager.GetString("MemberSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Configuration.
        /// </summary>
        internal static string NotificationConfiguration {
            get {
                return ResourceManager.GetString("NotificationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Authorization.
        /// </summary>
        internal static string OpenAuthorization {
            get {
                return ResourceManager.GetString("OpenAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Authorizations.
        /// </summary>
        internal static string OpenAuthorizations {
            get {
                return ResourceManager.GetString("OpenAuthorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Balance Report.
        /// </summary>
        internal static string OpenBalanceReport {
            get {
                return ResourceManager.GetString("OpenBalanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Requisition.
        /// </summary>
        internal static string OrderRequisition {
            get {
                return ResourceManager.GetString("OrderRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Card Transactions.
        /// </summary>
        internal static string P_CardTransactions {
            get {
                return ResourceManager.GetString("P-CardTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Categories.
        /// </summary>
        internal static string PartCategories {
            get {
                return ResourceManager.GetString("PartCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part/Price File Upload Report.
        /// </summary>
        internal static string PartPriceFileUploadReport {
            get {
                return ResourceManager.GetString("PartPriceFileUploadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Price Lookup.
        /// </summary>
        internal static string PartPriceLookup {
            get {
                return ResourceManager.GetString("PartPriceLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Purchases Report.
        /// </summary>
        internal static string PartPurchasesReport {
            get {
                return ResourceManager.GetString("PartPurchasesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Sales by Fleet Report.
        /// </summary>
        internal static string PartSalesByFleetReport {
            get {
                return ResourceManager.GetString("PartSalesByFleetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Sales by Shop Report.
        /// </summary>
        internal static string PartSalesByShopReport {
            get {
                return ResourceManager.GetString("PartSalesByShopReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Cross Reference.
        /// </summary>
        internal static string PartsCrossReference {
            get {
                return ResourceManager.GetString("PartsCrossReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Lookup.
        /// </summary>
        internal static string PartsLookup {
            get {
                return ResourceManager.GetString("PartsLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCard Error Invoices.
        /// </summary>
        internal static string PCardErrorInvoices {
            get {
                return ResourceManager.GetString("PCardErrorInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Billing Management Report.
        /// </summary>
        internal static string PendingBillingManagementReport {
            get {
                return ResourceManager.GetString("PendingBillingManagementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Discrepancy.
        /// </summary>
        internal static string PODiscrepancy {
            get {
                return ResourceManager.GetString("PODiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Discrepancy History.
        /// </summary>
        internal static string PODiscrepancyHistory {
            get {
                return ResourceManager.GetString("PODiscrepancyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Entry.
        /// </summary>
        internal static string POEntry {
            get {
                return ResourceManager.GetString("POEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Entry Aspx.
        /// </summary>
        internal static string POEntryAspx {
            get {
                return ResourceManager.GetString("POEntryAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Orders.
        /// </summary>
        internal static string POOrders {
            get {
                return ResourceManager.GetString("POOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POQ Entry.
        /// </summary>
        internal static string POQEntry {
            get {
                return ResourceManager.GetString("POQEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POQ Entry Aspx.
        /// </summary>
        internal static string POQEntryAspx {
            get {
                return ResourceManager.GetString("POQEntryAspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Transaction Lookup.
        /// </summary>
        internal static string POTransactionLookup {
            get {
                return ResourceManager.GetString("POTransactionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Detail.
        /// </summary>
        internal static string PriceDetail {
            get {
                return ResourceManager.GetString("PriceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Exception Report.
        /// </summary>
        internal static string PriceExceptionReport {
            get {
                return ResourceManager.GetString("PriceExceptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Lookup.
        /// </summary>
        internal static string PriceLookup {
            get {
                return ResourceManager.GetString("PriceLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group Rule Maintenance.
        /// </summary>
        internal static string ProductGroupRuleMaintenance {
            get {
                return ResourceManager.GetString("ProductGroupRuleMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group Rules Override.
        /// </summary>
        internal static string ProductGroupRulesOverride {
            get {
                return ResourceManager.GetString("ProductGroupRulesOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        internal static string PurchaseOrders {
            get {
                return ResourceManager.GetString("PurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Fleet Summary.
        /// </summary>
        internal static string PurchasingFleetSummary {
            get {
                return ResourceManager.GetString("PurchasingFleetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QlikView Dashboard.
        /// </summary>
        internal static string QlikViewDashboard {
            get {
                return ResourceManager.GetString("QlikViewDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate Accruals Report.
        /// </summary>
        internal static string RebateAccrualsReport {
            get {
                return ResourceManager.GetString("RebateAccrualsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Search.
        /// </summary>
        internal static string RelationshipSearch {
            get {
                return ResourceManager.GetString("RelationshipSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remittance Report.
        /// </summary>
        internal static string RemittanceReport {
            get {
                return ResourceManager.GetString("RemittanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Requests.
        /// </summary>
        internal static string ServiceRequests {
            get {
                return ResourceManager.GetString("ServiceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement File.
        /// </summary>
        internal static string SettlementFile {
            get {
                return ResourceManager.GetString("SettlementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement File Summary.
        /// </summary>
        internal static string SettlementFileSummary {
            get {
                return ResourceManager.GetString("SettlementFileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Summary Report.
        /// </summary>
        internal static string ShopSummaryReport {
            get {
                return ResourceManager.GetString("ShopSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-community Management.
        /// </summary>
        internal static string Sub_communityManagement {
            get {
                return ResourceManager.GetString("Sub-communityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Reconcile Report.
        /// </summary>
        internal static string SummaryReconcileReport {
            get {
                return ResourceManager.GetString("SummaryReconcileReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Remittance Report.
        /// </summary>
        internal static string SummaryRemittanceReport {
            get {
                return ResourceManager.GetString("SummaryRemittanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Center.
        /// </summary>
        internal static string SupportCenter {
            get {
                return ResourceManager.GetString("SupportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code Configuration.
        /// </summary>
        internal static string TaxCodeConfiguration {
            get {
                return ResourceManager.GetString("TaxCodeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Review Report.
        /// </summary>
        internal static string TaxReviewReport {
            get {
                return ResourceManager.GetString("TaxReviewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Activity.
        /// </summary>
        internal static string TransactionActivity {
            get {
                return ResourceManager.GetString("TransactionActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Credit.
        /// </summary>
        internal static string UpdateCredit {
            get {
                return ResourceManager.GetString("UpdateCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group Setup.
        /// </summary>
        internal static string UserGroupSetup {
            get {
                return ResourceManager.GetString("UserGroupSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Summary.
        /// </summary>
        internal static string VendorSummary {
            get {
                return ResourceManager.GetString("VendorSummary", resourceCulture);
            }
        }
    }
}
